root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - jest
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
env:
  jest/globals: true
parserOptions:
  project:
    - tsconfig.json
